name: pd_meshnet

channels:
  - conda-forge
  - pytorch
  - nvidia
  - pyg
dependencies:
  - pytorch
  - numpy
  - pytorch-cuda
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - pytorch-spline-conv
  - tensorboard  # optional
  # - pymesh
  - pyyaml


environment:
  THIRD_PARTY_ROOT: {{ root }}/third_party
  PYG_ROOT: {{ root }}/third_party/pytorch_geometric

#  CPATH:
#    #     export PATH=/usr/local/cuda-10.1/bin${PATH:+:${PATH}}
#    #    export CPATH=/usr/local/cuda-10.1/include:$CPATH
#    - $CONDA_PREFIX/include           # [unix]
#    - $CONDA_PREFIX/Library/include   # [win]

#  LD_LIBRARY_PATH: $CONDA_PREFIX/lib  # [unix]
# /usr/local/cuda-10.1/lib64

